spring.profiles.active=local
spring.application.name=SiteEntArtes
server.port=8080
spring.datasource.url=${BD_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
JWT_SECRET=${JWT_SECRET}
HASH_SECRET=${HASH_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=80MB
server.tomcat.max-part-count=20

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=escolaentartesbraga@gmail.com
spring.mail.password=${PASS_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true